version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - pip install --upgrade awscli
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.8.2/terraform_1.8.2_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - terraform -version
      - chmod +x send_email.sh

  pre_build:
    commands:
      - terraform init

  build:
    commands:
      - |
        echo "Running Terraform Plan"
        if ! terraform plan -out=tfplan; then
          ./send_email.sh "Terraform Plan Failed" "Terraform plan failed"
          exit 1
        fi

  post_build:
    commands:
      - |
        echo "Applying Terraform"
        if terraform apply -auto-approve tfplan; then
          terraform output > tf_output.txt
          ./send_email.sh "Terraform Success" "$(cat tf_output.txt)"
        else
          ./send_email.sh "Terraform Apply Failed" "Terraform apply failed"
          exit 1
        fi
